### ISSUE TITLE
"last metrics" are not reported to Datadog - Artillery exits

### ISSUE THREAD

**Issue by anroots** [bigbank-as/artillery-plugin-datadog#5]
The last metrics of an Artillery test (past ~15 secs?) are not reported to Datadog - Artillery main process exits before this is done. It is especially obvious with a short test, for example:

```yaml
# test.yaml
config:
  target: https://sqroot.eu
  phases:
    - duration: 3
      arrivalRate: 2
      name: "First stage"
  plugins:
    datadog:
      # Custom hostname (leave blank if not desired)
      host: 'test-host'
      # Custom metric prefix (defaults to 'artillery.')
      prefix: 'artillery.'
      # Additional tags for all metrics
      tags:
        - 'mode:test'
scenarios:
  - flow:
      - get:
          url: /
```

Running it...

```bash
$ DEBUG=metrics,plugin:datadog DATADOG_API_KEY=secret ./node_modules/.bin/artillery run test.yaml
```

... results in no metrics in Datadog.

Increasing the test duration to 20 seconds results in metrics reported. Probably a bug in the way the `done` event is handled or data is flushed.

Both versions `0.1` and `0.2` are affected -- needs investigation.
